name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "mail_db"
database_id = "4ee11004-b794-4645-8cda-672381c39c71"

[[kv_namespaces]]
binding = "kv"
id = "7c53a0dc88884557b311bfe8af6bbe0e"

[[r2_buckets]]
binding = "r2"
bucket_name = "mail-attach"

# [[send_email]]
# name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
# ai_model = ""
# analysis_cache = false
# orm_log = false
# domain = []
# admin = ""
# jwt_secret = ""

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
